"""Message handler for processing incoming messages and generating replies."""

from __future__ import annotations

import asyncio
from typing import Any, Protocol

import httpx

from xianyuflow_common import get_logger

from app.websocket import WebSocketConnectionPool

logger = get_logger(__name__)


class AIClient(Protocol):
    """Protocol for AI service client."""

    async def generate_reply(
        self,
        message: str,
        context: dict[str, Any],
    ) -> str | None:
        """Generate a reply using AI service.

        Args:
            message: The incoming message.
            context: Conversation context.

        Returns:
            Generated reply text or None if no reply needed.
        """
        ...


class MessageHandler:
    """Handles incoming messages and manages replies.

    Features:
    - Parse incoming messages
    - Determine if reply is needed
    - Call AI Service for reply generation
    - Send reply messages
    """

    def __init__(
        self,
        connection_pool: WebSocketConnectionPool,
        ai_service_url: str,
        auto_reply: bool = True,
        reply_delay: float = 1.0,
    ) -> None:
        """Initialize the message handler.

        Args:
            connection_pool: The WebSocket connection pool.
            ai_service_url: URL of the AI service.
            auto_reply: Whether to automatically reply to messages.
            reply_delay: Delay before sending reply (seconds).
        """
        self.connection_pool = connection_pool
        self.ai_service_url = ai_service_url
        self.auto_reply = auto_reply
        self.reply_delay = reply_delay
        self._http_client = httpx.AsyncClient(timeout=30.0)

        # Register as message handler
        self.connection_pool.add_message_handler(self._on_message)

        # Message types that require reply
        self._reply_triggers = {
            "text",
            "inquiry",
            "question",
            "price_inquiry",
            "shipping_inquiry",
        }

        # Message types to ignore
        self._ignored_types = {
            "system",
            "notification",
            "read_receipt",
            "typing",
        }

    async def close(self) -> None:
        """Close the handler and cleanup resources."""
        self.connection_pool.remove_message_handler(self._on_message)
        await self._http_client.aclose()

    def _on_message(self, account_id: str, message: dict[str, Any]) -> None:
        """Handle incoming message.

        Args:
            account_id: The account that received the message.
            message: The message data.
        """
        # Process message asynchronously
        asyncio.create_task(self._process_message(account_id, message))

    async def _process_message(
        self, account_id: str, message: dict[str, Any]
    ) -> None:
        """Process a message and generate reply if needed.

        Args:
            account_id: The account that received the message.
            message: The message data.
        """
        try:
            # Parse message
            parsed = self._parse_message(message)
            if not parsed:
                logger.debug("Message could not be parsed: %s", message)
                return

            msg_type = parsed.get("type", "unknown")
            msg_content = parsed.get("content", "")
            sender_id = parsed.get("sender_id", "")
            conversation_id = parsed.get("conversation_id", "")

            logger.info(
                "Received message from %s to account %s: [%s] %s",
                sender_id,
                account_id,
                msg_type,
                msg_content[:100],
            )

            # Check if we should ignore this message
            if self._should_ignore(msg_type, parsed):
                logger.debug("Ignoring message of type %s", msg_type)
                return

            # Check if reply is needed
            if not self._should_reply(msg_type, parsed):
                logger.debug("No reply needed for message of type %s", msg_type)
                return

            # Check if auto-reply is enabled
            if not self.auto_reply:
                logger.debug("Auto-reply is disabled")
                return

            # Build context for AI
            context = {
                "account_id": account_id,
                "sender_id": sender_id,
                "conversation_id": conversation_id,
                "message_type": msg_type,
                "message_content": msg_content,
                "timestamp": parsed.get("timestamp"),
                "metadata": parsed.get("metadata", {}),
            }

            # Generate reply using AI service
            reply_text = await self._generate_reply(msg_content, context)
            if not reply_text:
                logger.debug("No reply generated by AI")
                return

            # Apply reply delay
            if self.reply_delay > 0:
                await asyncio.sleep(self.reply_delay)

            # Send reply
            await self._send_reply(
                account_id=account_id,
                recipient_id=sender_id,
                conversation_id=conversation_id,
                content=reply_text,
            )

        except Exception as e:
            logger.error("Error processing message: %s", e)

    def _parse_message(self, message: dict[str, Any]) -> dict[str, Any] | None:
        """Parse incoming message into standard format.

        Args:
            message: Raw message data.

        Returns:
            Parsed message or None if invalid.
        """
        # Handle different message formats
        # Xianyu message format
        if "msgType" in message:
            return {
                "type": self._map_msg_type(message.get("msgType", "")),
                "content": message.get("content", ""),
                "sender_id": message.get("senderId", ""),
                "conversation_id": message.get("conversationId", ""),
                "timestamp": message.get("timestamp"),
                "metadata": message.get("ext", {}),
            }

        # Standard format
        if "type" in message:
            return {
                "type": message.get("type", "unknown"),
                "content": message.get("content", ""),
                "sender_id": message.get("sender_id", ""),
                "conversation_id": message.get("conversation_id", ""),
                "timestamp": message.get("timestamp"),
                "metadata": message.get("metadata", {}),
            }

        return None

    def _map_msg_type(self, xianyu_type: str) -> str:
        """Map Xianyu message type to internal type.

        Args:
            xianyu_type: Xianyu message type.

        Returns:
            Internal message type.
        """
        type_mapping = {
            "1": "text",
            "2": "image",
            "3": "voice",
            "4": "location",
            "5": "card",
            "100": "system",
        }
        return type_mapping.get(xianyu_type, "unknown")

    def _should_ignore(self, msg_type: str, parsed: dict[str, Any]) -> bool:
        """Check if message should be ignored.

        Args:
            msg_type: Message type.
            parsed: Parsed message data.

        Returns:
            True if message should be ignored.
        """
        if msg_type in self._ignored_types:
            return True

        # Ignore messages from self
        if parsed.get("sender_id") == parsed.get("account_id"):
            return True

        # Ignore empty messages
        if not parsed.get("content"):
            return True

        return False

    def _should_reply(self, msg_type: str, parsed: dict[str, Any]) -> bool:
        """Check if message needs a reply.

        Args:
            msg_type: Message type.
            parsed: Parsed message data.

        Returns:
            True if reply is needed.
        """
        # Always reply to trigger types
        if msg_type in self._reply_triggers:
            return True

        # Check content for keywords that indicate inquiry
        content = parsed.get("content", "").lower()
        inquiry_keywords = [
            "价格",
            "多少钱",
            "怎么卖",
            "运费",
            "包邮",
            "便宜",
            "最低",
            "在吗",
            "还有吗",
            "可以",
            "能不能",
        ]

        for keyword in inquiry_keywords:
            if keyword in content:
                return True

        return False

    async def _generate_reply(
        self, message: str, context: dict[str, Any]
    ) -> str | None:
        """Generate reply using AI service.

        Args:
            message: The incoming message.
            context: Conversation context.

        Returns:
            Generated reply text or None.
        """
        try:
            request_data = {
                "messages": [
                    {
                        "role": "system",
                        "content": self._build_system_prompt(context),
                    },
                    {"role": "user", "content": message},
                ],
                "temperature": 0.7,
                "max_tokens": 500,
            }

            response = await self._http_client.post(
                f"{self.ai_service_url}/api/v1/chat/completions",
                json=request_data,
            )
            response.raise_for_status()

            data = response.json()
            choices = data.get("choices", [])
            if choices:
                reply = choices[0].get("message", {}).get("content", "")
                return reply.strip() if reply else None

            return None

        except httpx.HTTPError as e:
            logger.error("HTTP error calling AI service: %s", e)
            return None
        except Exception as e:
            logger.error("Error generating reply: %s", e)
            return None

    def _build_system_prompt(self, context: dict[str, Any]) -> str:
        """Build system prompt for AI.

        Args:
            context: Conversation context.

        Returns:
            System prompt string.
        """
        return (
            "你是一个闲鱼卖家助手，帮助回复买家消息。"
            "回复要友好、专业、简洁。"
            "如果买家询问价格，提供合理的价格信息。"
            "如果询问运费，说明运费政策。"
            "保持礼貌，促成交易。"
        )

    async def _send_reply(
        self,
        account_id: str,
        recipient_id: str,
        conversation_id: str,
        content: str,
    ) -> bool:
        """Send reply message.

        Args:
            account_id: The account sending the reply.
            recipient_id: The recipient ID.
            conversation_id: The conversation ID.
            content: Reply content.

        Returns:
            True if sent successfully.
        """
        message = {
            "type": "text",
            "content": content,
            "recipient_id": recipient_id,
            "conversation_id": conversation_id,
            "timestamp": asyncio.get_event_loop().time(),
        }

        success = await self.connection_pool.send_message(account_id, message)
        if success:
            logger.info(
                "Reply sent from %s to %s: %s",
                account_id,
                recipient_id,
                content[:100],
            )
        else:
            logger.error("Failed to send reply from %s to %s", account_id, recipient_id)

        return success
